version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_DB: develop
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  currency-service:
    build:
      dockerfile: Dockerfile
    restart: always
    command:
      - "-e"
      - "develop"
    ports:
      - 8005:8005